Repository pl-o-plando/plo_web, pull requests merged in 2024-03, with the labels that each got.

#10 Refactor/9 tailwind 적용, App.css 수정
  src/App.css
  src/index.css
  src/pages/SignIn.js
  src/pages/SignUp.js
  src/styles/SignIn.css
Labels: refactor

#12 Refactor/11 Sidebar 수정
  src/component/SideBar.js
  src/styles/SideBar.css
Labels: refactor

#14 Feat/13 로그인, 회원가입 유효성 검사
  package-lock.json
  package.json
  src/App.css
  src/index.css
  src/pages/SignIn.js
  src/pages/SignUp.js
Labels: feat

#16 Refactor/15 회원가입 유효성 추가
  src/index.css
  src/pages/SignUp.js
Labels: refactor

#19 Design/17 메인페이지 틀 퍼블리싱 #17
  package-lock.json
  package.json
  src/App.js
  src/component/Main/Calendar.js
  src/component/Main/Todo/CategoryAndTodo.js
  src/component/Main/Todo/Todo.js
  src/component/Main/Todo/TodoComponent.js
  src/pages/Main.js
Labels: design

#22 Design/18 Diary 퍼블리싱
  package-lock.json
  src/component/Main/Diary/DiaryShow.js
  src/component/Main/Diary/NoDiary.js
  src/pages/Main.js
Labels: design

#23 Design/21 모달창 퍼블리싱
  src/component/Main/Todo/CategoryAndTodo.js
  src/component/Main/Todo/Todo.js
  src/component/Main/Todo/TodoComponent.js
  src/component/Modal/AddModal.js
  src/component/Modal/DetailModal.js
  src/component/Modal/DoingTodoModal.js
  src/component/Modal/Dropdown.js
  src/component/Modal/PlusModal.js
  src/component/Modal/RoutineModal.js
  src/component/Modal/TodoDropdownModal.js
  src/styles/Modal.css
Labels: design

#25 Refactor/24 회원가입 페이지 수정
  src/pages/SignUp.js
Labels: refactor

#27 Chore/26 recoil 설치 및 날짜 전역 관리
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/recoil/dateState.js
Labels: chore

#32 Feat/28 메인페이지 날짜 선택 기능 구현 및 TodoComponent 기본값 설정
  src/component/Main/Calendar.js
  src/component/Main/Todo/TodoComponent.js
  src/component/Modal/TodoDropdownModal.js
  src/recoil/dateState.js
Labels: feat

#34 Refactor/33 sidebar 수정 및 라우터 연결
  src/component/SideBar.js
  src/styles/SideBar.css
Labels: refactor

#37 Feat/35 통계 페이지 날짜 구현
  package-lock.json
  package.json
  src/App.js
  src/component/Statistic/ShowWeek.js
Labels: feat
